spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/tracker_db?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/tracker_db?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    whitelabel:
      enabled: false